In [ ]:
pip install numpy

In [2]:
import numpy as np

In [3]:
list1 = [1.3, 2., 3, 4, 5]
arr = np.array(list1)
print(arr, type(arr), arr.dtype)

[1.3 2.  3.  4.  5. ] <class 'numpy.ndarray'> float64


In [4]:
list2 = [[1, 2], [3, 4]]
print(list2)
arr1 = np.array(list2)
print(arr1, type(arr1), arr1.dtype)

[[1, 2], [3, 4]]
[[1 2]
 [3 4]] <class 'numpy.ndarray'> int64


In [5]:
a = np.array([[1,2], [3,4]])
print(a)
b = np.array([[10,20], [30,40]])
print(b)

[[1 2]
 [3 4]]
[[10 20]
 [30 40]]


In [6]:
print(a.shape)
print(a.ndim)
print(a.dtype)
print(a.itemsize)
print(a.size)

(2, 2)
2
int64
8
4


In [7]:
c = a + b
print(c)

[[11 22]
 [33 44]]


In [8]:
d = b - a
print(d)

[[ 9 18]
 [27 36]]


In [9]:
e = a * b
print(e)

[[ 10  40]
 [ 90 160]]


In [10]:
f = a @ b
print(f)

[[ 70 100]
 [150 220]]


In [11]:
f = np.matmul(a, b)
print(f)

[[ 70 100]
 [150 220]]


In [12]:
mat1 = np.array([[1,2,3], [4,5,6]])
print(mat1)
print(mat1.shape, mat1.ndim)

[[1 2 3]
 [4 5 6]]
(2, 3) 2


In [13]:
mat2 = np.array([[10,20,30], [40,50,60], [70,80,90]])
print(mat2)
print(mat2.shape, mat2.ndim)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
(3, 3) 2


In [14]:
mat3 = mat1 @ mat2
print(mat3, mat3.shape, mat3.ndim)
mat4 = np.matmul(mat1, mat2)
print(mat4, mat4.shape, mat4.ndim)

[[300 360 420]
 [660 810 960]] (2, 3) 2
[[300 360 420]
 [660 810 960]] (2, 3) 2


In [15]:
mat3 = np.zeros((2,3))
print(mat3)

[[0. 0. 0.]
 [0. 0. 0.]]


In [18]:
mat4 = np.ones((2,3))
print(mat4)

[[1. 1. 1.]
 [1. 1. 1.]]


In [19]:
mat5 = np.full((2,3), 100)
print(mat5)

[[100 100 100]
 [100 100 100]]


In [20]:
mat6 = np.full((3,4), 5)
print(mat6)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [21]:
mat7 = np.eye(3)
print(mat7)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [22]:
mat8 = np.random.random((3, 4))
print(mat8)

[[0.8638215  0.44938454 0.03552998 0.46410158]
 [0.39650072 0.36536734 0.02666309 0.95068792]
 [0.26437589 0.41901339 0.70999555 0.29853283]]


In [25]:
print(range(0, 10))

range(0, 10)


In [24]:
a = np.arange(0, 10)
print(a)
print(type(a), a.shape, a.ndim)

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'> (10,) 1


In [26]:
b = np.arange(0, 10, 2)
print(b)
c = np.arange(0, 1.0, 0.2)
print(c)

[0 2 4 6 8]
[0.  0.2 0.4 0.6 0.8]


In [27]:
d = np.arange(0, 10).reshape(2, 5)
print(d, d.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]] (2, 5)


In [28]:
e = np.arange(0, 10).reshape(5, 2)
print(e)
f = np.arange(0, 12).reshape(3, 4)
print(f)
g = np.arange(0, 18).reshape(3, 6)
print(g)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]


In [29]:
arr = np.arange(0, 24).reshape(4, 3, 2)
print(arr, arr.shape, arr.ndim)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]] (4, 3, 2) 3


In [30]:
np.arange(0, 40).reshape(5, 4, 2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]],

       [[32, 33],
        [34, 35],
        [36, 37],
        [38, 39]]])

In [31]:
np.arange(0, 40).reshape(5, 4, -1)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]],

       [[32, 33],
        [34, 35],
        [36, 37],
        [38, 39]]])

In [32]:
arr1 = np.arange(3)
print(arr1)
arr2 = arr1 + 5
print(arr2)

[0 1 2]
[5 6 7]


In [33]:
arr1 = np.ones((3, 3))
print(arr1, arr1.shape)
arr2 = np.arange(3)
print(arr2, arr2.shape)
arr3 = arr1 + arr2
print(arr3, arr3.shape)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] (3, 3)
[0 1 2] (3,)
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]] (3, 3)


In [34]:
arr1 = np.arange(3).reshape(3, 1)
print(arr1, arr1.shape)
arr2 = np.arange(3)
print(arr2, arr2.shape)
arr3 = arr1 + arr2
print(arr3, arr3.shape)

[[0]
 [1]
 [2]] (3, 1)
[0 1 2] (3,)
[[0 1 2]
 [1 2 3]
 [2 3 4]] (3, 3)


In [35]:
a = np.arange(0, 4)
print(a)
print(a[1], a[3])

[0 1 2 3]
1 3


In [36]:
b = np.arange(6).reshape(3,2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [37]:
print(b[0])
print(b[0, 1]) # 1
print(b[2, 0]) # 4
print(b[1, 1]) # 3


[0 1]
1
4
3


In [38]:
c = np.arange(24).reshape(4,3,2)
print(c)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]


In [39]:
print(c[1])
print(c[1, 1])
print(c[2, 2, 1])

[[ 6  7]
 [ 8  9]
 [10 11]]
[8 9]
17


In [40]:
arr = np.array([1,2,3,4,5])
print(arr, arr.dtype)

[1 2 3 4 5] int64


In [41]:
f_arr = arr.astype(np.float64)
print(f_arr, f_arr.dtype)

[1. 2. 3. 4. 5.] float64


In [42]:
n1 = np.random.randint(0, 5)
n2 = np.random.randint(7)
print(n1, n2)

3 0


In [43]:
np.random.randint(1, 46)

24

In [44]:
np.random.rand(10)

array([0.27186416, 0.81245181, 0.8414318 , 0.79560559, 0.12157754,
       0.4861238 , 0.86829233, 0.97517463, 0.9198012 , 0.93291236])

In [45]:
np.random.rand(2, 3)

array([[0.68435036, 0.16717889, 0.92233608],
       [0.48328801, 0.20185482, 0.24818696]])

In [46]:
np.random.rand(2, 3, 4)

array([[[0.00806753, 0.91545842, 0.64653859, 0.10051072],
        [0.70779227, 0.878503  , 0.8032081 , 0.53561576],
        [0.58587479, 0.72095464, 0.19232671, 0.61484118]],

       [[0.12153573, 0.49313643, 0.69066192, 0.20056874],
        [0.88860955, 0.80975062, 0.18895   , 0.0316494 ],
        [0.06112334, 0.70736548, 0.28900636, 0.93508743]]])

In [47]:
np.random.randn(5)

array([ 1.04305449, -0.3583296 , -0.75517044, -1.53100646,  0.54166393])

In [48]:
np.random.randn(4, 5)

array([[-1.14817824, -2.16974141, -0.68165579,  0.05927827, -0.83509849],
       [-1.32222991, -0.04631776,  0.73083453, -0.25664717,  0.02684633],
       [-1.23859369,  0.32714684, -1.1480124 , -0.05848533, -0.96042728],
       [ 1.3785198 , -0.40924853, -1.41862245,  1.36409905, -1.41967133]])

In [49]:
np.random.randn(3,4,5)

array([[[ 1.20945701,  0.36327712, -0.82008726, -0.52644842,
          1.16607733],
        [ 1.60633257,  1.8481242 ,  0.12150595,  0.62336534,
          0.85705466],
        [ 1.67970905, -0.35660134, -0.10713445, -1.79442849,
         -1.73268507],
        [ 0.60319688, -0.27314989,  0.14522696,  0.42706392,
          0.10296311]],

       [[-0.77387476, -0.63582963, -1.3499778 ,  1.49658902,
          1.52494159],
        [ 1.01708666, -0.77873395, -0.34949073, -0.63909179,
          0.62928495],
        [-0.35187498,  0.08830809, -0.57570282, -1.59816657,
         -1.43160509],
        [ 0.33073244, -1.30299385,  0.03169905, -0.8578783 ,
          0.11751138]],

       [[-0.6153932 ,  0.90927597,  1.41446145, -0.21276059,
         -0.68264815],
        [-0.79976001, -0.26344939,  0.05152616,  0.15651402,
          0.49922922],
        [ 0.37091174, -0.38474079,  0.36634627,  0.04078298,
          0.95911304],
        [ 0.72816104, -1.04609574, -0.65359802, -1.20410933,
         -1

In [50]:
arr = np.arange(10)
print(arr)
np.random.shuffle(arr)
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[7 8 6 3 1 4 0 2 5 9]


In [51]:
arr1 = np.arange(24).reshape(4,6)
print(arr1)
np.random.shuffle(arr1)
print(arr1)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13 14 15 16 17]
 [ 0  1  2  3  4  5]
 [18 19 20 21 22 23]
 [ 6  7  8  9 10 11]]


In [52]:
arr2 = np.arange(24).reshape(4, 3, 2)
np.random.shuffle(arr2)

arr23 = arr1.reshape(3,2,4)
print(arr23)

arr32 = arr2.reshape(4, 6)
print(arr32)

[[[12 13 14 15]
  [16 17  0  1]]

 [[ 2  3  4  5]
  [18 19 20 21]]

 [[22 23  6  7]
  [ 8  9 10 11]]]
[[18 19 20 21 22 23]
 [12 13 14 15 16 17]
 [ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [54]:
arr = np.arange(12).reshape(3,4)
print(arr)
print(arr.sum())
print(arr.sum(axis=0))
print(arr.sum(axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
66
[12 15 18 21]
[ 6 22 38]


In [55]:
arr = np.arange(24).reshape(4,3,2)
print(arr)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]


In [56]:
print(arr.sum())
print(arr.sum(axis=0))

276
[[36 40]
 [44 48]
 [52 56]]


In [57]:
print(arr.sum(axis=1))
print(arr.sum(axis=2))

[[ 6  9]
 [24 27]
 [42 45]
 [60 63]]
[[ 1  5  9]
 [13 17 21]
 [25 29 33]
 [37 41 45]]


In [58]:
print(arr.sum(axis=(1, 2)))

[ 15  51  87 123]
